export const stateList = {
  "andaman-nicobar-islands": "Andaman & Nicobar Islands",
  "andhra-pradesh": "Andhra Pradesh",
  "arunachal-pradesh": "Arunachal Pradesh",
  assam: 'Assam',
  bihar: 'Bihar',
  chandigarh: 'Chandigarh',
  chhattisgarh: 'Chhattisgarh',
  "dadra-nagar-haveli": "Dadra & Nagar Haveli",
  "daman-diu": "Daman & Diu",
  delhi: 'Delhi',
  goa: 'Goa',
  gujarat: 'Gujarat',
  haryana: 'Haryana',
  "himachal-pradesh": "Himachal Pradesh",
  "jammu-kashmir": "Jammu & Kashmir",
  jharkhand: 'Jharkhand',
  karnataka: 'Karnataka',
  kerala: 'Kerala',
  ladakh: 'Ladakh',
  lakshadweep: 'Lakshadweep',
  "madhya-pradesh": "Madhya Pradesh",
  maharashtra: 'Maharashtra',
  manipur: 'Manipur',
  meghalaya: 'Meghalaya',
  mizoram: 'Mizoram',
  nagaland: 'Nagaland',
  odisha: 'Odisha',
  puducherry: 'Puducherry',
  punjab: 'Punjab',
  rajasthan: 'Rajasthan',
  sikkim: 'Sikkim',
  "tamil-nadu": "Tamil Nadu",
  telangana: 'Telangana',
  tripura: 'Tripura',
  uttarakhand: 'Uttarakhand',
  "uttar-pradesh": "Uttar Pradesh",
  "west-bengal": "West Bengal",
};
